config/routes.rb
SketchMerge::Application.routes.draw do
  get "home/index"
  devise_for :users
  match '/dashboard' => "home#dashboard", :as => :user_root
  post '/events/update', :to => 'events#update'
  post '/events/create' ,:to => 'events#create'
  post '/events/destroy', :to => 'events#destroy'
  post '/merges/create', :to => 'merges#create'
  post '/merges/destroy', :to => 'merges#destroy'
  get  '/merges/find_time'

  root :to => 'home#index'

end

app/models/event.rb
require "event_range"
class Event < ActiveRecord::Base
  attr_accessible :day_index, :end_time, :start_time, :user_id
  belongs_to :user
  def to_blocks_of_minutes(mins)
    temp_time = start_time
    times = []
    until temp_time == end_time
      times.push temp_time.strftime("%A %r")
      temp_time += mins.minutes
    end
    times
  end
  def self.construct_ranges(time_hash)
    day_ranges ={}
    time_hash.each_pair do |day,times|
      day_ranges[day] = EventRange.time_ranges(times)
    end
    day_ranges
  end
end

app/models/merge.rb
class Merge < ActiveRecord::Base
  belongs_to :user
  belongs_to :receiver, :class_name => "User", :foreign_key => "receiver_id"
  attr_accessible :pending, :user_id, :receiver_id

  def self.generate_create_json(current_user,to_user)
    if to_user != current_user.username
      if User.exists?(:username => to_user)
        if current_user.merges.exists?(:receiver_id => User.where("username = ?", to_user)) or
            User.where("username = ?", to_user).first.merges.exists?(:receiver_id => current_user.id)
          {:error => "You already have merged with '#{to_user}'!"}
        else
          new_merge = current_user.merges.create(:receiver_id => User.where("username = ?", to_user).first.id)
          merge_json = {}
          merge_json["to_username"] = new_merge.receiver.username
          merge_json["merge_id"] = new_merge.id
          merge_json
        end
      else
        {:error => "User with username '#{to_user}' does not exist!"}
      end
    else
      {:error => "You cannot add yourself as a merger!"}
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  has_many :events, :dependent => :destroy
  has_many :merges
  has_many :received_merges, :class_name => "Merge", :foreign_key => "receiver_id"

  validates_presence_of :username
  validates_uniqueness_of :username
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  attr_accessor :login
  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,:username,:login
  # attr_accessible :title, :body
  def consolidate_events
    result = []
    events.each do |event|
      result = result | event.to_blocks_of_minutes(15)
    end
    result
  end
  def merge_with_other_users(user_list)
    all_times = consolidate_events
    return {:error => "You have no available times! No one can meet with you! Edit the calendar to mark you availability and try again."} if all_times.empty?
    user_list.each do |user|
      all_times = all_times & user.consolidate_events
      if all_times.empty?
        return {:error => "No possible meeting times exist with '#{user_list.map{|x| x.username}.join(',')}'. Try removing a user to continue."}
      end
    end
    Event.construct_ranges(all_times.group_by{|x| x.split.first})
  end
  
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :authenticate_user!
  def update
    event = current_user.events.find(params["event_id"].to_i)
    event.start_time = DateTime.parse(params["new_start_time"].gsub(/\sGMT.+\z/,''))
    event.end_time = DateTime.parse(params["new_end_time"].gsub(/\sGMT.+\z/,''))
    event.save!
    render :json => event, :status => :ok
  end
  def create
    datetime = DateTime.parse("#{params["eventDate"]} #{params["eventTime"]}")
    event = current_user.events.create(:start_time => datetime, 
                                       :end_time => (datetime + 15.minutes))
    data = {:begins => event.start_time.strftime("%F %T"), 
      :ends =>event.end_time.strftime("%F %T") , 
      :uid => event.id, :color => "blue"}.to_json
    render :json => data, :status => :ok
  end
  def destroy
    current_user.events.find(params["event_id"].to_i).delete
    render :json => {}, :status => :ok
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!, :only => :dashboard
  def index
  end
  def dashboard
    @events = current_user.events
    @merges = current_user.merges | current_user.received_merges
    gon.start_date = Time.now.beginning_of_week(:sunday).strftime("%Y-%m-%d")
    gon.jbuilder
  end
end

app/controllers/merges_controller.rb
class MergesController < ApplicationController
  before_filter :authenticate_user!
  def create
    render :json => Merge.generate_create_json(current_user,params[:to_username])
  end

  def destroy
    merge = Merge.find(params[:merge_id].to_i)
    if merge
      merge.delete
    end
    render :json => {success:true} 
  end

  def find_time
    render :json => current_user.merge_with_other_users(params[:to_users].map{|x| User.find_by_username(x)})
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper

end

app/helpers/home_helper.rb
module HomeHelper

end

app/helpers/merges_helper.rb
module MergesHelper
end

app/views/home/_info_calendar.html.erb
<div class="alert fade in alert-info alert-block">
	<button type="button" class="close" data-dismiss="alert">&times;</button>
	<h4>Getting Started</h4>
	Welcome to SketchMerge! It looks like you do not have any available times yet.  To mark your 
	availability just click on the calendar below, times can be dragged and resized just like 
	Google Calendar!
</div>

app/views/home/_info_merge.html.erb
<div class="alert fade in alert-info alert-block">
	<button type="button" class="close" data-dismiss="alert">&times;</button>
	<h4>Getting Started</h4>
	Welcome to SketchMerge! This area is where your merges are listed.  A merge is another user
	who you wish to meet with.  When you add a merge using the field below it will be listed here with a checkbox.  Clicking that checkbox will show the times in which both of you are available to meet (this can be done with as many users as desired!).
</div>

app/views/home/_merge.html.erb
<%merges.each do |merge|%>
    <tr>
        <% if merge.user == current_user %>
             <td><input type="checkbox" class="ajax_checkbox" name="merge"data-receiver="<%=merge.receiver.username%>"></td>
             <td><%=merge.receiver.username%></td>
          <td><button type="button" class="btn btn-danger merge_delete" data-merge="<%=merge.id%>">Delete</button></td>
           <%else%>
          <td><input type="checkbox" class="ajax_checkbox" name="merge" data-receiver="<%=merge.user.username%>"></td>
          <td><%=merge.user.username%></td>
          <td><button type="button" class="btn btn-danger merge_delete" data-merge="<%=merge.id%>">Delete</button></td>
        <%end %>
  	</tr>
<% end %>

app/views/home/dashboard.html.erb
<h1 class="lead">Your `Sketch</h1>
<hr>
<% if current_user.events.count == 0 %>
	<%= render "info_calendar"%>
<% end %>
<div id="calendar">
	
</div>
<h1 class="lead">Your Merges</h1>
<% unless Merge.exists?(:receiver_id => current_user.id) || Merge.exists?(:user_id =>current_user.id) %>
  <%= render "info_merge"%>
<% end %>
<div id="merges">
  <table class="table table-hover" id="merge_table">
	<tr>
		<th><i class="icon-ok"></i></th><th>Username</th><th>Actions</th>
	</tr>
    <%= render :partial => "merge", :locals => {:merges => @merges}%>
  </table>
  <div id="warning_zone">
  </div>
  <div class="input-append" id="add_user_div">
    <input class="span2" id="username_search" type="text" placeholder="User's Username">
    <button class="btn" id="add_user_button" type="button">Add User</button>
  </div>
</div>
<h1 class="lead">Your Possible Times</h1>
<div id="possible_times">
	<div class="alert fade in" id="times_alert">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <strong>Error!</strong> No merges selected, no possible times exist.
    </div>
</div>

app/views/home/index.html.erb
<div class="jumbotron">
        <h1 id="intro">The best way to find time to meet with your teammates,coworkers and friends.</h1>
        <p class="lead" id="leaddesc">SketchMerge is a simple utility that allows two or more people to find time to meet with one another.  A great tool for any team.</p>
		<div style="max-width: 400px; margin: 0 auto 10px;" class="well">
	    	<%= link_to "Sign Up", new_user_registration_path, :class =>"btn btn-large btn-block btn-success", :id => "signup" %>
		    <%= link_to "Sign In", new_user_session_path,  :class =>"btn btn-large btn-block btn-primary", :id => "signin"%>   
		</div>
</div>

app/views/layouts/_messages.html.erb
<% if notice %>
<p class="notice"><%= notice %></p>
<% end %>
<% if alert %>
 <p class="alert"><%= alert %></p>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="masthead">
<% if current_user %>
  <ul class="nav nav-pills pull-right">
    <%= active_link_to "Dashboard", user_root_path,:wrap_tag => :li%>
    <%= active_link_to "Logout", destroy_user_session_path ,:wrap_tag => :li%>
    <%= active_link_to "Edit Profile", edit_user_registration_path,:wrap_tag => :li%>
  </ul>
<% end %>
<h3 class="muted">SketchMerge  
	<% if current_user %>
	<small>(Logged in as '<%=current_user.username%>')</small>
	<% end %>
</h3>
</div>
<hr>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SketchMerge</title>
  <%= include_gon%>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
    <%= render "layouts/navigation" %>
    <%= render "layouts/messages" %>
	<%= yield %>
</div>
</body>
<footer>
	<ul class="inline">
    <li><%= link_to "@elliomax", "https://twitter.com/elliomax" ,:target => "_blank"%></li>
	<li>|</li>
    <li><%= link_to "Found a bug or issue?", "mailto:elliott.432@buckeyemail.osu.edu"%></li>
    </ul>
</footer>
</html>

app/views/merges/create.html.erb
<h1>Merges#create</h1>
<p>Find me in app/views/merges/create.html.erb</p>